## Modifying the array elements using insert, append and delete

<img center src='./images/axis_0.jpg' />

In [1]:
import numpy as np

In [2]:
a = np.arange(10,19)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

**Syntax**
 - np.append(ndarray, elements you want to add, axis)

In [3]:
np.append(a,21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 21])

In [4]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [5]:
np.append(a,[21,22,23])

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 21, 22, 23])

In [6]:
b = np.append(a,[21,22,23])
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 21, 22, 23])

In [7]:
b.reshape(4,3)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [21, 22, 23]])

In [8]:
b.reshape(3,4)

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 21, 22, 23]])

In [9]:
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 21, 22, 23])

In [10]:
c1 = b.reshape(3,4)
c1

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 21, 22, 23]])

In [11]:
c1 = np.append(c1,[[11,12,13,14]],axis=0)
c1

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 21, 22, 23],
       [11, 12, 13, 14]])

In [12]:
c2 = b.reshape(3,4)
print(c2)


[[10 11 12 13]
 [14 15 16 17]
 [18 21 22 23]]


In [13]:
c2 = np.append(c2,[[31],[32],[33]],axis=1)
print(c2)

[[10 11 12 13 31]
 [14 15 16 17 32]
 [18 21 22 23 33]]


In [29]:
c1 = b.reshape(3,4)
c1 = np.append(c1,[[11,12,13,14]],axis=0)
# c1
print(c1)
c2 = b.reshape(3,4)
c2 = np.append(c2,[[31],[32],[33]],axis=1)
print(c2)

[[10 11 12 13]
 [14 15 16 17]
 [18 21 22 23]
 [11 12 13 14]]
[[10 11 12 13 31]
 [14 15 16 17 32]
 [18 21 22 23 33]]


- For 2D arrays - rows and columns insertion <br/>
**Syntax**
    - np.insert(ndarray, index, elements,axis)

In [19]:
arr1 = np.array([[101,102],[103,104]])
print(np.insert(arr1,1,[111,112],axis = 0))
np.insert(arr1,1,[111,112],axis = 1)

[[101 102]
 [111 112]
 [103 104]]


array([[101, 111, 102],
       [103, 112, 104]])

#### Integer array indexing:

In [30]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

'''
     0,1
0 - [1,2] 
1 - [3,4] 
2 - [5,6] 
'''

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"
a[[0, 0], [1, 1]]

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[1 4 ]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [31]:
import numpy as np

# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

#                              0  1   2
print(a)  # prints 0 "array([[ 1,  2,  3],
          #        1        [ 4,  5,  6],
          #        2        [ 7,  8,  9],
          #        3        [10, 11, 12]])"

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


#### Difference between vector , matrix and tesor

In [33]:
vector = np.arange(5)
print("Vector shape:", vector.shape)

matrix = np.ones([3, 2])
print("Matrix shape:", matrix.shape)

tensor = np.zeros([2, 3, 3])
print("Tensor shape:", tensor.shape)

Vector shape: (5,)
Matrix shape: (3, 2)
Tensor shape: (2, 3, 3)


##### Generating ones with numpy np

In [4]:
import numpy as np
print('Vector with Ones {} \n'.format(np.ones(10)))

print('\n Square matrix with Ones {} \n'.format(np.ones((5,5))))

Vector with Ones [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 


 Square matrix with Ones [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 



##### Creating arrays using existing arrays

In [36]:
x = np.array([[1, 2, 3], [4, 5, 6]])

np.full(x.shape, 29)

array([[29, 29, 29],
       [29, 29, 29]])

#### Creating an indentity matrix

In [37]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
np.eye(5, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [39]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))


[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [40]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w)) # (9*11 + 10*12 = 219)
print(np.dot(v, w)) # (9*11 + 10*12 = 219)

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))


219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [1]:
 # 2D arrays or matrices
import numpy as np
a = [[1,2,3],[2,0,3],[7,-5,1]]
b = [[3,-1,5],[-2,-6,4], [0,4,4]]
z = np.dot(a,b)
 
# [1 2 3]    [3 -1 5]
# [2 0 3]    [-2 -6 4]
# [7 -5 1]   [0  4  4] 
print(z)

[[-1 -1 25]
 [ 6 10 22]
 [31 27 19]]


####  Inner product

In [2]:
a = np.array([[1,2,3], [4,-1,0]])
b = np.array([6,3,2])
z = np.inner(a,b)
print(z) 

[18 21]


In [3]:
a

array([[ 1,  2,  3],
       [ 4, -1,  0]])

In [4]:
b

array([6, 3, 2])

In [5]:
b.shape

(3,)

In [7]:
a.T

array([[ 1,  4],
       [ 2, -1],
       [ 3,  0]])

In [67]:
###The same results can be obtained using the dot method as follows.

a.dot(b.T)

array([18, 21])

**Outer Product**

Outer product is the dot product of a column vector of size M by 1 and r
a row vector of size 1 by N. The resulting array is a matrix of size M*N.

In [70]:
a = np.array([1,2,3,4,5])
b = np.array([6,3,2])
z = np.outer(a,b)
print(z)

[[ 6  3  2]
 [12  6  4]
 [18  9  6]
 [24 12  8]
 [30 15 10]]


**Matrix Multiplication**

In [71]:
a = np.arange(6).reshape(2,3)
b = np.arange(-3,3).reshape(3,2)
z = np.matmul(a, b)
print(a) 
print(b) 
print(z)

[[0 1 2]
 [3 4 5]]
[[-3 -2]
 [-1  0]
 [ 1  2]]
[[ 1  4]
 [-8  4]]


In [72]:
### @ symbol can be used for matrix multuplication
a = np.random.random([8,7,5,2])
b = np.random.random([8,7,2,3])
z = a @ b
print(z.shape) 

(8, 7, 5, 3)


**Matrix Determinant**

Matrix determinant can be calculated using the method det available in the linalg module.

In [77]:
 # generate a random integer matrix of size 3 by 3
a = np.random.randint(3,35,[3,3])
print(a)
det = np.linalg.det(a)
print(int(det)) 
# * det = 18 * (17*17 - 17*33) - 19 * (27*17 - 33*33) + 13 (27*17 - 33*17)

[[18 19 13]
 [27 17 33]
 [33 17 17]]
5747


**Matrix Inverse**

Inverse of a square matrix can be derived using the inv method of the linalg module.

In [78]:
a = np.random.randint(1,10,[3,3])
inv = np.linalg.inv(a)
print(a)
print()
print(inv) 

[[1 8 9]
 [5 9 1]
 [6 5 3]]

[[-0.07073955 -0.06752412  0.23472669]
 [ 0.02893891  0.16398714 -0.1414791 ]
 [ 0.09324759 -0.13826367  0.09967846]]


###### Performing numpy array operations

In [1]:
import numpy as np

x = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

45
[12 15 18]
[ 6 15 24]


In [42]:
import numpy as np

x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


###### Using broadcasting on numpy arrays

In [43]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


#### Memory address of numpy

In [44]:
x = np.array([1, 2, 3], dtype=np.int32)
x.data

In [45]:
### memory address of data
x.__array_interface__['data'][0] 

1987114935296

In [46]:
x.__array_interface__  

{'data': (1987114935296, False),
 'strides': None,
 'descr': [('', '<i4')],
 'typestr': '<i4',
 'shape': (3,),
 'version': 3}

#### Reversing the elements

In [48]:
x = np.array([1, 2, 3, 4, 5, 6], dtype=np.int32)
y = x[::-1]
y

array([6, 5, 4, 3, 2, 1])

In [56]:
### Number of bytes it jumps 
#### strides: the number of bytes to jump to find the next element
#### 1 stride per dimension


y.strides

(-4,)

In [54]:
x1 = np.array([1, 2, 3, 4, 5, 6], dtype=np.int32)
y1 = x1[::-2]
y1

array([6, 4, 2])

In [55]:
y1.strides

(-8,)

In [60]:
y = x[2:]
y
y.__array_interface__['data'][0]

1987114934536

In [61]:
x.__array_interface__['data'][0]

1987114934528

In [62]:
y.__array_interface__['data'][0] - x.__array_interface__['data'][0]

8

In [64]:
x = np.zeros((10, 10, 10), dtype=np.float64)
x.strides

(800, 80, 8)