* We can specify the data type while creating the numpy array as follows

In [3]:
import numpy as np

In [4]:
arr1 = [
    [4, 0, 0],
    [0, 4, 0],
    [0, 0, 4]
]


arr1 = np.array(arr1, dtype=np.int16)

In [5]:
arr1

array([[4, 0, 0],
       [0, 4, 0],
       [0, 0, 4]], dtype=int16)

* Creating a zero matrix

In [6]:
m4 = np.zeros((4, 3), dtype=np.uint8)

In [7]:
m4

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint8)

* Creating a matrix with all ones

In [9]:
oneM = np.ones((5, 4), dtype=float)
print(oneM)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


* Creating an square identity matrix using numpy

In [11]:
eMat = np.eye(5)
eMat

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

* Using the math module to create matrices

In [12]:
import math

In [14]:
x_coords = np.linspace(-2 * math.pi, 2 * math.pi, 50)
x_coords

array([-6.28318531, -6.02672876, -5.77027222, -5.51381568, -5.25735913,
       -5.00090259, -4.74444605, -4.48798951, -4.23153296, -3.97507642,
       -3.71861988, -3.46216333, -3.20570679, -2.94925025, -2.6927937 ,
       -2.43633716, -2.17988062, -1.92342407, -1.66696753, -1.41051099,
       -1.15405444, -0.8975979 , -0.64114136, -0.38468481, -0.12822827,
        0.12822827,  0.38468481,  0.64114136,  0.8975979 ,  1.15405444,
        1.41051099,  1.66696753,  1.92342407,  2.17988062,  2.43633716,
        2.6927937 ,  2.94925025,  3.20570679,  3.46216333,  3.71861988,
        3.97507642,  4.23153296,  4.48798951,  4.74444605,  5.00090259,
        5.25735913,  5.51381568,  5.77027222,  6.02672876,  6.28318531])

In [15]:
y_values = np.array([math.sin(x) for x in x_coords])
y_values

array([ 2.44929360e-16,  2.53654584e-01,  4.90717552e-01,  6.95682551e-01,
        8.55142763e-01,  9.58667853e-01,  9.99486216e-01,  9.74927912e-01,
        8.86599306e-01,  7.40277997e-01,  5.45534901e-01,  3.15108218e-01,
        6.40702200e-02, -1.91158629e-01, -4.33883739e-01, -6.48228395e-01,
       -8.20172255e-01, -9.38468422e-01, -9.95379113e-01, -9.87181783e-01,
       -9.14412623e-01, -7.81831482e-01, -5.98110530e-01, -3.75267005e-01,
       -1.27877162e-01,  1.27877162e-01,  3.75267005e-01,  5.98110530e-01,
        7.81831482e-01,  9.14412623e-01,  9.87181783e-01,  9.95379113e-01,
        9.38468422e-01,  8.20172255e-01,  6.48228395e-01,  4.33883739e-01,
        1.91158629e-01, -6.40702200e-02, -3.15108218e-01, -5.45534901e-01,
       -7.40277997e-01, -8.86599306e-01, -9.74927912e-01, -9.99486216e-01,
       -9.58667853e-01, -8.55142763e-01, -6.95682551e-01, -4.90717552e-01,
       -2.53654584e-01, -2.44929360e-16])

* Using copy() method to create a new matrix

In [21]:
import numpy as np 
mat1 = np.arange(12)
mat1

mat2 = mat1.reshape(4,3)
mat2.shape

mat3 = mat1.reshape(3,4).copy() # Creates a new copy of the matrix
print('Matrix1 is : \n{}\n'.format(mat1))
print('Matrix2 is : \n{}\n'.format(mat2))
print('Matrix3 is : \n{}'.format(mat3))

Matrix1 is : 
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Matrix2 is : 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Matrix3 is : 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


* Stacking in numpy
  - When vertical stacking is performed each array must have the same number of columns.

  - When horizontal stacking is performed, each array must have the same number of rows.


In [24]:
import numpy as np

b1 = np.arange(11, 16)
print('b1 vecotr is {}'.format(b1))

c2 = np.arange(21, 31).reshape(2, 5)
print('c2 matrix is {}'.format(c2))

d1 = np.vstack((b1, c2))
print('d1 matrix is stacked vertically {}'.format(d1))


b1 vecotr is [11 12 13 14 15]
c2 matrix is [[21 22 23 24 25]
 [26 27 28 29 30]]
d1 matrix is stacked vertically [[11 12 13 14 15]
 [21 22 23 24 25]
 [26 27 28 29 30]]


* Performing Vector Operations using numpy

In [25]:
v1 = np.array([1, 2, 3])
print('Vector v1 is {} '.format(v1))

Vector v1 is [1 2 3] 


* Addition of vectors

In [34]:
v1 = np.array(list(range(5)))
print(f"vec1 is {v1}\n")

v2 = np.array(list(range(6,11)))
print(f"vec2 is {v2}\n")

v3 = v1 + v2
print(f"sum of v1 and v2 = {v3}\n")

vec1 is [0 1 2 3 4]

vec2 is [ 6  7  8  9 10]

sum of v1 and v2 = [ 6  8 10 12 14]



* Vector Subtraction:

In [35]:
v4 = v2 - v1
print(f"Subtractig v1 from v2 gives =  {v4}")

Subtractig v1 from v2 gives =  [6 6 6 6 6]


* Vector Multiplication:

In [36]:
v5 = v1 * v2
print(f"Vector multiplication of v1 and v2 is {v5}\n")

Vector multiplication of v1 and v2 is [ 0  7 16 27 40]



* Vector Division:

In [37]:
v6 = v1 / v2
print(f"Vector Division of v1 and v2 is  {v6}")

Vector Division of v1 and v2 is  [0.         0.14285714 0.25       0.33333333 0.4       ]


* Vector Dot product

In [38]:
vd = v1.dot(v2)
print(f"Dot product of v1 and v2 is {vd}")


Dot product of v1 and v2 is 90


* Scalar Multiplication of a vector

In [39]:
v9 = np.array([2, 4, 6])
print(f'scalar product of v9 and 5 is {v9*5}')

scalar product of v9 and 5 is [10 20 30]


* L1 Norm and L2 Norm
  - We import the linalg package and norm module to compute l1 norm and l2 norm
  - L1 norm is the sum of the absolute vector values. It is the norm is a calculation of the Manhattan distance from the origin of the vector space
  - L2 norm is the square root of the sum of the squares of the vectors. L2 norm is also called as the eucledian norm

In [40]:
from numpy import array, inf
from numpy.linalg import norm

In [42]:
v = np.array([2,3,4,5,6])
l2 = norm(v)
print(f"l2 norm is given by {l2}")

l2 norm is given by 9.486832980505138


### Working with Matrices
A matrix is a two dimensional data structure where the data is arranged into rows and columns.
          
$$          
A = \begin{pmatrix}
2 & -6 & -11 & 0\\       
4 & 6 & 13 & -9\\
4 & 7 & 12 & -2
\end{pmatrix}
$$

values ---> [2 -6 -11 0] represent rows <br/>
values below are columns : 

$$ \begin{pmatrix}
2\\
4\\
4\\
\end{pmatrix}
$$

* Lets perform some operations on the below matrix

In [46]:
A = np.matrix([[4, 6, 2],
               [5, 7, 19],
               [0, 3, 12]])
A

matrix([[ 4,  6,  2],
        [ 5,  7, 19],
        [ 0,  3, 12]])

In [47]:
B = np.matrix([[16, -4, 12],
               [4, 4, 5],
               [5, 5, 1]])
B

matrix([[16, -4, 12],
        [ 4,  4,  5],
        [ 5,  5,  1]])

* Compute the following
  
- $6A$ (or any other scalar multiple of $A$);
- $A ^ 3$ (or any other exponent of $A$);
- $A + B$;
- $A - B$;
- $AB$

In [48]:
6*A

matrix([[ 24,  36,  12],
        [ 30,  42, 114],
        [  0,  18,  72]])

In [49]:
A ** 3

matrix([[ 544, 1218, 3212],
        [ 900, 2395, 7146],
        [ 345, 1092, 3525]])

In [50]:
A + B

matrix([[20,  2, 14],
        [ 9, 11, 24],
        [ 5,  8, 13]])

In [51]:
A - B

matrix([[-12,  10, -10],
        [  1,   3,  14],
        [ -5,  -2,  11]])

In [52]:
A*B

matrix([[ 98,  18,  80],
        [203, 103, 114],
        [ 72,  72,  27]])

* Transpose of a matrix

In [55]:
A = np.array([[2,3],[4,5],[6,7]])
print(A.transpose())

[[2 4 6]
 [3 5 7]]


In [56]:
A.T

array([[2, 4, 6],
       [3, 5, 7]])

* Matrix elements can be accessed using the index

In [57]:
A[0]

array([2, 3])

In [59]:
A[1]

array([4, 5])

In [61]:
A[0][0]

2

In [62]:
A[0][1]

3

* Compute the determinant of a matrix

In [66]:
array1 = np.array([[4, 3], 
                  [5, 6]])
detValue = np.linalg.det(array1)
print(detValue)


9.000000000000002
